SELECT    
  COLUNAS.COLUMN_NAME AS COLUNA_KEY,
  case COLUNAS.COLUMN_NAME
FROM    
  USER_TABLES TABELA,   
  USER_TAB_COLUMNS COLUNAS   
WHERE    
  TABELA.TABLE_NAME = COLUNAS.TABLE_NAME   
  AND TABELA.TABLE_NAME = 'NOME_DA_SUA_TABELA_BANCO';
                      

